In [1]:
# ============================================
# GEOPULSE - SYNTHETIC MOBILITY DATA
# ============================================

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Reproducible random data
np.random.seed(42)

# Number of GPS pings
n = 5000

# Generate IDs
ping_ids = [f"P{str(i).zfill(5)}" for i in range(1, n + 1)]
user_ids = [f"U{str(np.random.randint(1, 1001)).zfill(4)}" for _ in range(n)]

# Fictional city center
center_lat = 28.6200
center_lon = 77.2100

# Generate GPS coordinates around the city
latitudes = np.random.normal(center_lat, 0.025, n)
longitudes = np.random.normal(center_lon, 0.025, n)

# Generate timestamps over 30 days
start_date = datetime(2026, 1, 1)

timestamps = [
    start_date + timedelta(
        days=int(np.random.randint(0, 30)),
        hours=int(np.random.randint(0, 24)),
        minutes=int(np.random.randint(0, 60)),
        seconds=int(np.random.randint(0, 60))
    )
    for _ in range(n)
]

# Sort timestamps
timestamps = sorted(timestamps)

# Movement types
movement_types = np.random.choice(
    ["Walking", "Driving", "Public Transport"],
    size=n,
    p=[0.50, 0.30, 0.20]
)

# Device types
device_types = np.random.choice(
    ["Mobile", "Tablet"],
    size=n,
    p=[0.90, 0.10]
)

# Create DataFrame
mobility_df = pd.DataFrame({
    "ping_id": ping_ids,
    "anonymous_user_id": user_ids,
    "timestamp": timestamps,
    "latitude": latitudes.round(6),
    "longitude": longitudes.round(6),
    "device_type": device_types,
    "movement_type": movement_types
})

# Add date and time-related columns
mobility_df["date"] = mobility_df["timestamp"].dt.date
mobility_df["hour"] = mobility_df["timestamp"].dt.hour
mobility_df["day_of_week"] = mobility_df["timestamp"].dt.day_name()

# Save CSV
mobility_df.to_csv("mobility_pings.csv", index=False)

print("mobility_pings.csv created successfully!")
print("Rows:", len(mobility_df))
print("\nFirst 5 rows:")
display(mobility_df.head())

mobility_pings.csv created successfully!
Rows: 5000

First 5 rows:

,ping_id,anonymous_user_id,timestamp,latitude,longitude,device_type,movement_type,date,hour,day_of_week
0,P00001,U0103,2026-01-01 00:13:42,28.616127,77.197509,Mobile,Walking,2026-01-01,0,Thursday
1,P00002,U0436,2026-01-01 00:21:11,28.637518,77.208469,Mobile,Driving,2026-01-01,0,Thursday
2,P00003,U0861,2026-01-01 00:44:45,28.613040,77.234882,Tablet,Walking,2026-01-01,0,Thursday
3,P00004,U0271,2026-01-01 00:45:35,28.635834,77.195544,Mobile,Walking,2026-01-01,0,Thursday
4,P00005,U0107,2026-01-01 00:46:53,28.581480,77.237832,Mobile,Walking,2026-01-01,0,Thursday

In [2]:
# ============================================
# GEOPULSE - SYNTHETIC STORE DATA
# ============================================

import pandas as pd

stores_data = {
    "store_id": [
        "S001", "S002", "S003", "S004", "S005",
        "S006", "S007", "S008", "S009", "S010"
    ],
    
    "store_name": [
        "GeoCafe Central",
        "GeoCafe Market",
        "GeoCafe Riverside",
        "GeoCafe Station",
        "GeoCafe Downtown",
        "GeoCafe Mall",
        "GeoCafe University",
        "GeoCafe TechPark",
        "GeoCafe North",
        "GeoCafe South"
    ],
    
    "latitude": [
        28.6205,
        28.6300,
        28.6050,
        28.6250,
        28.6150,
        28.6400,
        28.6100,
        28.6350,
        28.6500,
        28.5900
    ],
    
    "longitude": [
        77.2100,
        77.2200,
        77.2050,
        77.2300,
        77.1950,
        77.2150,
        77.2250,
        77.1950,
        77.2100,
        77.2200
    ],
    
    "store_type": [
        "High Street",
        "Market",
        "Riverside",
        "Transit",
        "Downtown",
        "Shopping Mall",
        "University",
        "Tech Park",
        "High Street",
        "Residential"
    ],
    
    "daily_capacity": [
        450, 400, 350, 500, 550,
        700, 300, 600, 400, 350
    ],
    
    "opening_date": [
        "2024-01-15",
        "2024-03-10",
        "2024-05-20",
        "2024-07-01",
        "2024-09-15",
        "2025-01-10",
        "2025-02-15",
        "2025-04-20",
        "2025-06-10",
        "2025-08-01"
    ]
}

stores_df = pd.DataFrame(stores_data)

# Convert opening date to datetime
stores_df["opening_date"] = pd.to_datetime(stores_df["opening_date"])

# Save CSV
stores_df.to_csv("stores.csv", index=False)

print("stores.csv created successfully!")
print("Rows:", len(stores_df))
print("\nStore data:")
display(stores_df)

stores.csv created successfully!
Rows: 10

Store data:

,store_id,store_name,latitude,longitude,store_type,daily_capacity,opening_date
0,S001,GeoCafe Central,28.6205,77.210,High Street,450,2024-01-15
1,S002,GeoCafe Market,28.6300,77.220,Market,400,2024-03-10
2,S003,GeoCafe Riverside,28.6050,77.205,Riverside,350,2024-05-20
3,S004,GeoCafe Station,28.6250,77.230,Transit,500,2024-07-01
4,S005,GeoCafe Downtown,28.6150,77.195,Downtown,550,2024-09-15
5,S006,GeoCafe Mall,28.6400,77.215,Shopping Mall,700,2025-01-10
6,S007,GeoCafe University,28.6100,77.225,University,300,2025-02-15
7,S008,GeoCafe TechPark,28.6350,77.195,Tech Park,600,2025-04-20
8,S009,GeoCafe North,28.6500,77.210,High Street,400,2025-06-10
9,S010,GeoCafe South,28.5900,77.220,Residential,350,2025-08-01

In [10]:
# ============================================
# GEOPULSE - SYNTHETIC CITY ZONES
# ============================================

import pandas as pd

zones_data = {
    "zone_id": [
        "Z001",
        "Z002",
        "Z003",
        "Z004",
        "Z005",
        "Z006",
        "Z007",
        "Z008"
    ],
    
    "zone_name": [
        "Central Business District",
        "North Market",
        "South Residential",
        "East Transit Hub",
        "West Riverside",
        "University District",
        "Tech Park",
        "Shopping District"
    ],
    
    "zone_type": [
        "Commercial",
        "Commercial",
        "Residential",
        "Transport",
        "Recreation",
        "Education",
        "Business",
        "Retail"
    ],
    
    "min_latitude": [
        28.610,
        28.630,
        28.580,
        28.615,
        28.595,
        28.600,
        28.625,
        28.630
    ],
    
    "max_latitude": [
        28.630,
        28.660,
        28.610,
        28.640,
        28.615,
        28.620,
        28.645,
        28.650
    ],
    
    "min_longitude": [
        77.195,
        77.195,
        77.195,
        77.220,
        77.180,
        77.215,
        77.180,
        77.205
    ],
    
    "max_longitude": [
        77.225,
        77.230,
        77.230,
        77.250,
        77.210,
        77.240,
        77.215,
        77.235
    ]
}

zones_df = pd.DataFrame(zones_data)

# Save CSV
zones_df.to_csv("zones.csv", index=False)

print("zones.csv created successfully!")
print("Rows:", len(zones_df))
print("\nZone data:")
display(zones_df)

zones.csv created successfully!
Rows: 8

Zone data:

,zone_id,zone_name,zone_type,min_latitude,max_latitude,min_longitude,max_longitude
0,Z001,Central Business District,Commercial,28.610,28.630,77.195,77.225
1,Z002,North Market,Commercial,28.630,28.660,77.195,77.230
2,Z003,South Residential,Residential,28.580,28.610,77.195,77.230
3,Z004,East Transit Hub,Transport,28.615,28.640,77.220,77.250
4,Z005,West Riverside,Recreation,28.595,28.615,77.180,77.210
5,Z006,University District,Education,28.600,28.620,77.215,77.240
6,Z007,Tech Park,Business,28.625,28.645,77.180,77.215
7,Z008,Shopping District,Retail,28.630,28.650,77.205,77.235

Duplicate rows in Mobility Data: 0
Duplicate rows in Store Data: 0
Duplicate rows in Zone Data: 0

In [15]:
import pandas as pd

mobility_df = pd.read_csv("mobility_pings.csv")
stores_df = pd.read_csv("stores.csv")
zones_df = pd.read_csv("zones.csv")

print("All datasets loaded successfully!")

print("Mobility Data:", mobility_df.shape)
print("Stores Data:", stores_df.shape)
print("Zones Data:", zones_df.shape)

#column names
print("MOBILITY COLUMNS")
print(mobility_df.columns.tolist())

print("\nSTORE COLUMNS")
print(stores_df.columns.tolist())

print("\nZONE COLUMNS")
print(zones_df.columns.tolist())

#First 5 rows
print("----- MOBILITY DATA -----")
display(mobility_df.head())

print("----- STORE DATA -----")
display(stores_df.head())

print("----- ZONE DATA -----")
display(zones_df.head())

#missing
print("Missing values in Mobility Data:")
display(mobility_df.isnull().sum())

print("\nMissing values in Store Data:")
display(stores_df.isnull().sum())

print("\nMissing values in Zone Data:")
display(zones_df.isnull().sum())

#duplicate 
print("Duplicate rows in Mobility Data:", mobility_df.duplicated().sum())
print("Duplicate rows in Store Data:", stores_df.duplicated().sum())
print("Duplicate rows in Zone Data:", zones_df.duplicated().sum())

#gps coordinate check
print("Latitude range:")
print(mobility_df["latitude"].min(), "to", mobility_df["latitude"].max())

print("\nLongitude range:")
print(mobility_df["longitude"].min(), "to", mobility_df["longitude"].max())

#timestamp converted into actual datetime
print(mobility_df["timestamp"].dtype)
mobility_df["timestamp"] = pd.to_datetime(mobility_df["timestamp"])

print(mobility_df["timestamp"].dtype)

#basic summary
mobility_df.describe()

All datasets loaded successfully!
Mobility Data: (5000, 10)
Stores Data: (10, 7)
Zones Data: (8, 7)
MOBILITY COLUMNS
['ping_id', 'anonymous_user_id', 'timestamp', 'latitude', 'longitude', 'device_type', 'movement_type', 'date', 'hour', 'day_of_week']

STORE COLUMNS
['store_id', 'store_name', 'latitude', 'longitude', 'store_type', 'daily_capacity', 'opening_date']

ZONE COLUMNS
['zone_id', 'zone_name', 'zone_type', 'min_latitude', 'max_latitude', 'min_longitude', 'max_longitude']
----- MOBILITY DATA -----

,ping_id,anonymous_user_id,timestamp,latitude,longitude,device_type,movement_type,date,hour,day_of_week
0,P00001,U0103,2026-01-01 00:13:42,28.616127,77.197509,Mobile,Walking,2026-01-01,0,Thursday
1,P00002,U0436,2026-01-01 00:21:11,28.637518,77.208469,Mobile,Driving,2026-01-01,0,Thursday
2,P00003,U0861,2026-01-01 00:44:45,28.613040,77.234882,Tablet,Walking,2026-01-01,0,Thursday
3,P00004,U0271,2026-01-01 00:45:35,28.635834,77.195544,Mobile,Walking,2026-01-01,0,Thursday
4,P00005,U0107,2026-01-01 00:46:53,28.581480,77.237832,Mobile,Walking,2026-01-01,0,Thursday

----- STORE DATA -----

,store_id,store_name,latitude,longitude,store_type,daily_capacity,opening_date
0,S001,GeoCafe Central,28.6205,77.210,High Street,450,2024-01-15
1,S002,GeoCafe Market,28.6300,77.220,Market,400,2024-03-10
2,S003,GeoCafe Riverside,28.6050,77.205,Riverside,350,2024-05-20
3,S004,GeoCafe Station,28.6250,77.230,Transit,500,2024-07-01
4,S005,GeoCafe Downtown,28.6150,77.195,Downtown,550,2024-09-15

----- ZONE DATA -----

,zone_id,zone_name,zone_type,min_latitude,max_latitude,min_longitude,max_longitude
0,Z001,Central Business District,Commercial,28.610,28.630,77.195,77.225
1,Z002,North Market,Commercial,28.630,28.660,77.195,77.230
2,Z003,South Residential,Residential,28.580,28.610,77.195,77.230
3,Z004,East Transit Hub,Transport,28.615,28.640,77.220,77.250
4,Z005,West Riverside,Recreation,28.595,28.615,77.180,77.210

Missing values in Mobility Data:

ping_id              0
anonymous_user_id    0
timestamp            0
latitude             0
longitude            0
device_type          0
movement_type        0
date                 0
hour                 0
day_of_week          0
dtype: int64

Missing values in Store Data:

store_id          0
store_name        0
latitude          0
longitude         0
store_type        0
daily_capacity    0
opening_date      0
dtype: int64

Missing values in Zone Data:

zone_id          0
zone_name        0
zone_type        0
min_latitude     0
max_latitude     0
min_longitude    0
max_longitude    0
dtype: int64

Duplicate rows in Mobility Data: 0
Duplicate rows in Store Data: 0
Duplicate rows in Zone Data: 0
Latitude range:
28.530448 to 28.701003

Longitude range:
77.116064 to 77.298602
object
datetime64[ns]

                           timestamp     latitude    longitude         hour
count                           5000  5000.000000  5000.000000  5000.000000
mean   2026-01-16 00:11:14.179800064    28.619236    77.209885    11.472800
min              2026-01-01 00:13:42    28.530448    77.116064     0.000000
25%    2026-01-08 11:25:54.750000128    28.602426    77.192754     5.000000
50%              2026-01-15 22:52:24    28.619096    77.209637    11.000000
75%              2026-01-23 11:05:50    28.636323    77.227070    17.000000
max              2026-01-30 23:59:16    28.701003    77.298602    23.000000
std                              NaN     0.025052     0.025324     6.908575